baseURL = "inejc.github.io/nejc-ilenic-photography/"
title = "Nejc Ilenic Photography"
author = "Nejc Ilenic"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

enableEmoji = true
hasCJKLanguage = false

pygmentsstyle = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

publishDir = "docs"

[params]
  sitename = "Nejc Ilenic Photography"
  # faviconfile = "images/favicon.png"
  uselatex = true
  progressively = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.primary]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.primary]]
    name = "About"
    url = "/about/"
    weight = 2
